# Generated by Django 3.2.12 on 2022-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='День Рождения'),
        ),
    ]
